# cucumber.andon.yml
pipelines:
  Cucumber:
    #environment_variables:   
    group: Acceptance_testing
    materials:
      cucumber:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/jaheikki/cucumber-selenide-allure.git
        branch: master
        destination: cucumber-selenide-allure
        whitelist: # monitor changes only for this component
          - cucumber.andon.yml/**/*.*
    stages:
      - acceptance_tests: # name of stage
          jobs:
            run_firefox_on_browserstack: # name of the job
              andon: # andon job configuration
                image: "andon.artifactorypro.shared.pub.tds.tieto.com/andon-gocd-agent-java8-maven3:v17.10.0" # elastic agent image
                #sonarqube: true
                ui_def_secure_variables:
                  - BROWSERSTACK_ACCESS_KEY
                ui_def_variables:
                  - BROWSERSTACK_USERNAME
#                selenium_grid:
#                  version: "2.53.1"
#                  browsers:
#                    - chrome
#                    - firefox
#                deploy_env:
#                  docker_compose:
#                    - "cucumber-selenide-allure/src/test/resources/docker-compose.yml"
              artifacts:
               - test:
                   source: cucumber-selenide-allure/target/site/allure-maven-plugin/
               #- test:
               #    source: ci/hus-ci-tests/target/hustests.log
              tabs:
                Report: cucumber-selenide-allure/target/site/allure-maven-plugin/index.html 
              tasks:
               - exec: # For debug
                   run_if: passed
                   command: bash
                   arguments:
                    - "-c"
                    - "echo $BROWSERSTACK_USERNAME && echo $BROWSERSTACK_ACCESS_KEY"
               - exec:
                   run_if: passed
                   command: bash
                   arguments:
                    - "-c"
                    - "export BROWSERSTACK_USERNAME && export BROWSERSTACK_ACCESS_KEY && cd cucumber-selenide-allure&&ls -ltr&&pwd&&mvn clean install -Denv=remote -Dcucumber.options=\"--plugin io.qameta.allure.cucumberjvm.AllureCucumberJvm --tags @simple_test\" -Dbrowser=microservice.browser.Firefox53WindowsRemoteDriverProvider"
               - exec: # Generate test report
                   run_if: any
                   command: bash
                   arguments:
                    - "-c"
                    - "cd cucumber-selenide-allure&&ls -ltr&&pwd&&mvn allure:report"
            run_chrome_on_browserstack: # name of the job
              andon: # andon job configuration
                image: "andon.artifactorypro.shared.pub.tds.tieto.com/andon-gocd-agent-java8-maven3:v17.10.0" # elastic agent image
                #sonarqube: true
                ui_def_secure_variables:
                  - BROWSERSTACK_ACCESS_KEY
                ui_def_variables:
                  - BROWSERSTACK_USERNAME
              artifacts:
               - test:
                   source: cucumber-selenide-allure/target/site/allure-maven-plugin/
              tabs:
                Report: cucumber-selenide-allure/target/site/allure-maven-plugin/index.html
              tasks:
               - exec:
                   run_if: passed
                   command: bash
                   arguments:
                    - "-c"
                    - "export BROWSERSTACK_USERNAME && export BROWSERSTACK_ACCESS_KEY && cd cucumber-selenide-allure&&ls -ltr&&pwd&&mvn clean install -Denv=remote -Dcucumber.options=\"--plugin io.qameta.allure.cucumberjvm.AllureCucumberJvm --tags @simple_test\" -Dbrowser=microservice.browser.Chrome61MacRemoteDriverProvider"
               - exec: # Generate test report
                   run_if: any
                   command: bash
                   arguments:
                    - "-c"
                    - "cd cucumber-selenide-allure&&ls -ltr&&pwd&&mvn allure:report"
            run_samsung_mobile_on_browserstack: # name of the job
              andon: # andon job configuration
                image: "andon.artifactorypro.shared.pub.tds.tieto.com/andon-gocd-agent-java8-maven3:v17.10.0" # elastic agent image
                #sonarqube: true
                ui_def_secure_variables:
                  - BROWSERSTACK_ACCESS_KEY
                ui_def_variables:
                  - BROWSERSTACK_USERNAME
              artifacts:
               - test:
                   source: cucumber-selenide-allure/target/site/allure-maven-plugin/
              tabs:
                Report: cucumber-selenide-allure/target/site/allure-maven-plugin/index.html
              tasks:
               - exec:
                   run_if: passed
                   command: bash
                   arguments:
                    - "-c"
                    - "export BROWSERSTACK_USERNAME && export BROWSERSTACK_ACCESS_KEY && cd cucumber-selenide-allure&&ls -ltr&&pwd&&mvn clean install -Denv=remote -Dcucumber.options=\"--plugin io.qameta.allure.cucumberjvm.AllureCucumberJvm --tags @simple_test\" -Dbrowser=microservice.browser.SamsungGalaxyS7_V6_0_RemoteDriverProvider"
               - exec: # Generate test report
                   run_if: any
                   command: bash
                   arguments:
                    - "-c"
                    - "cd cucumber-selenide-allure&&ls -ltr&&pwd&&mvn allure:report"
